version: '3'

services:
  heimdall:
    # https://hub.docker.com/r/linuxserver/heimdall/
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - config_heimdall:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  plex:
    # https://hub.docker.com/r/linuxserver/plex/
    image: linuxserver/plex  
    container_name: plex  
    environment:
      - VERSION=latest
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - config_plex:/config
      - plex_movies:/data/movies
      - plex_tv:/data/tv
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    restart: unless-stopped

  radarr:
    # https://hub.docker.com/r/linuxserver/radarr/
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - config_radarr:/config
      - plex_movies:/movies
      - downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  sabnzbd:
    # https://hub.docker.com/r/linuxserver/sabnzbd/
    image: linuxserver/sabnzbd 
    container_name: sabnzbd 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    volumes:
      - config_sabnzbd:/config
      - downloads_incomplete:/incomplete-downloads
      - downloads:/downloads
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped

  sonarr:
    # https://hub.docker.com/r/linuxserver/sonarr/
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
    ports:
      - "8989:8989"
    volumes:
      - config_sonarr:/config
      - plex_tv:/tv
      - downloads:/downloads
    restart: unless-stopped

volumes:
  config_heimdall:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/heimdall/
      o: bind
  config_plex:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/plex/
      o: bind
  config_radarr:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/radarr/
      o: bind
  config_sabnzbd:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/sabnzbd/
      o: bind
  config_sonarr:
    driver: local
    driver_opts:
      type: none
      device: $PWD/configs/sonarr/
      o: bind
  downloads:
  downloads_incomplete:
  plex_movies:
    driver: local
    driver_opts:
      type: none
      device: ${PLEX_PATH}/movies/
      o: bind
  plex_tv:
    driver: local
    driver_opts:
      type: none
      device: ${PLEX_PATH}/tv/
      o: bind